### PR TITLE
Fix issue in which header would sometimes overlap TOC

### LINKED ISSUE #69: Header logo sometimes overlaps TOC
When scrolling the page up sometimes the osquery logo overlaps the top of the tables TOC.

osquery-header-toc

### PR DESCRIPTION
**Pull request by taylorkearns**
Simplifies the logic for the sticky TOC: if the header is visible, set the TOC to static. If the header isn't visible, fix the TOC to the upper corner.

toc-scroll

Fixes #69

### CODE REVIEW

File: src/pages/Schema/Schema.js [hunk 1]
```diff
@@ -228,7 +232,7 @@ class Schema extends Component {
     })
 
     return (
-      <div className={classes} id={`${baseClass}-toc`}>
```
Comment (nhpace) [inline src/pages/Schema/Schema.js]: did this class in the scss need to get nuked?

Comment (taylorkearns) [reply src/pages/Schema/Schema.js]: Yea because we were using it [here](https://github.com/osquery/osquery-site/pull/82/files#diff-89a20d32d554469b96bb7f04c61ef1f3L59) but we removed that code.
